export enum ErrorCode {
  // Auth
  AUTH_EMPTY_PASSWORD = 'AUTH_EMPTY_PASSWORD',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_EMAIL = 'AUTH_INVALID_EMAIL',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // System
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
