export enum ErrorCode {
  // AUTH
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_CREATE_USER_ERROR = 'AUTH_CREATE_USER_ERROR',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMPTY_REFRESH_TOKEN = 'AUTH_EMPTY_REFRESH_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // COMMON
  FORBIDDEN_EXCEPTION = 'FORBIDDEN_EXCEPTION',

  // DEMOGRAPHIC
  FEDERATION_ACRONYM_ALREAY_EXISTS = 'FEDERATION_ACRONYM_ALREAY_EXISTS',
  FEDERATION_ACRONYM_EMPTY = 'FEDERATION_ACRONYM_EMPTY',
  FEDERATION_CREATION_ERROR = 'FEDERATION_CREATION_ERROR',
  FEDERATION_NAME_ALREAY_EXISTS = 'FEDERATION_NAME_ALREAY_EXISTS',
  FEDERATION_NAME_EMPTY = 'FEDERATION_NAME_EMPTY',
  FEDERATION_NOT_FOUND = 'FEDERATION_NOT_FOUND',

  CONTINENT_NOT_FOUND = 'CONTINENT_NOT_FOUND',

  NATION_NOT_FOUND = 'NATION_NOT_FOUND',

  // SIGN [IN | OUT | UP]
  SIGN_EMAIL_EMPTY = 'SIGN_EMAIL_EMPTY',
  SIGN_EMAIL_INVALID = 'SIGN_EMAIL_INVALID',
  SIGN_PASSWORD_EMPTY = 'SIGN_PASSWORD_EMPTY',
  SIGN_PASSWORD_NO_LOWERCASE = 'SIGN_PASSWORD_NO_LOWERCASE',
  SIGN_PASSWORD_NO_NUMBER = 'SIGN_PASSWORD_NO_NUMBER',
  SIGN_PASSWORD_NO_SYMBOL = 'SIGN_PASSWORD_NO_SYMBOL',
  SIGN_PASSWORD_NO_UPPERCASE = 'SIGN_PASSWORD_NO_UPPERCASE',
  SIGN_NAME_TOO_SHORT = 'SIGN_NAME_TOO_SHORT',
  SIGN_PASSWORD_TOO_SHORT = 'SIGN_PASSWORD_TOO_SHORT',
  SIGN_NAME_EMPTY = 'SIGN_NAME_EMPTY',
  SIGN_USER_ALREADY_EXISTS = 'SIGN_USER_ALREADY_EXISTS',

  // USER
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
