export enum ErrorCode {
  // AUTH
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_CREATE_USER_ERROR = 'AUTH_CREATE_USER_ERROR',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMPTY_REFRESH_TOKEN = 'AUTH_EMPTY_REFRESH_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS',

  // SIGN [IN | OUT | UP]
  SIGN_EMAIL_EMPTY = 'SIGN_EMAIL_EMPTY',
  SIGN_EMAIL_INVALID = 'SIGN_EMAIL_INVALID',
  SIGN_AUTH_PASSWORD_EMPTY = 'SIGN_AUTH_PASSWORD_EMPTY',
  SIGN_AUTH_PASSWORD_NO_LOWERCASE = 'SIGN_AUTH_PASSWORD_NO_LOWERCASE',
  SIGN_AUTH_PASSWORD_NO_NUMBER = 'SIGN_AUTH_PASSWORD_NO_NUMBER',
  SIGN_AUTH_PASSWORD_NO_SYMBOL = 'SIGN_AUTH_PASSWORD_NO_SYMBOL',
  SIGN_AUTH_PASSWORD_NO_UPPERCASE = 'SIGN_AUTH_PASSWORD_NO_UPPERCASE',
  SIGN_AUTH_NAME_TOO_SHORT = 'SIGN_AUTH_NAME_TOO_SHORT',
  SIGN_AUTH_PASSWORD_TOO_SHORT = 'SIGN_AUTH_PASSWORD_TOO_SHORT',
  SIGN_AUTH_NAME_EMPTY = 'SIGN_AUTH_NAME_EMPTY',

  // USER
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
