services:
  api:
    build: .
    container_name: myfm_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    container_name: myfm_postgres
    restart: always
    environment:
      POSTGRES_USER: myfm_user
      POSTGRES_PASSWORD: myfm_password
      POSTGRES_DB: myfm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
