services:
  db:
    container_name: myfm-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: myfm-api
    image: myfm-api
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
