version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: fm_postgres
    restart: always
    environment:
      POSTGRES_USER: fm_user
      POSTGRES_PASSWORD: fm_password
      POSTGRES_DB: my_fm_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
