name: Railway Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - run: npm install
      - run: npm test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service MyFM
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
