name: Revert Migration

on:
  workflow_dispatch:

jobs:
  revert-migration:
    name: Revert Migration
    runs-on: ubuntu-latest

    environment: PRD
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - run: npm install
      - run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Revert last migration
        run: railway run --service backend --environment production "npm run migration:revert:prod"
